[package]
name = "v3"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3", features = ["Document", "HtmlButtonElement", "Event", "Window", "MouseEvent", "console", "NodeList"] }

[lib]
crate-type = ["cdylib"]
